# Generated by Django 5.0 on 2024-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='apto_agendamento',
            field=models.BooleanField(default=False),
        ),
    ]
