# Generated by Django 5.0 on 2024-01-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidato_apto_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='teve_covid_recentemente',
            field=models.BooleanField(default=False),
        ),
    ]
