# Generated by Django 5.0 on 2024-01-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_candidato_teve_covid_recentemente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='apto_agendamento',
        ),
    ]
