# Generated by Django 5.0 on 2024-01-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_candidato_apto_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelicimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=7, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('logadouro', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
    ]
