# Generated by Django 5.0 on 2024-01-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_estabelicimento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estabelicimento',
            new_name='Estabelecimento',
        ),
    ]
