# Generated by Django 5.0 on 2024-01-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_estabelicimento_estabelecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
