# Generated by Django 5.0 on 2024-01-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_estabelecimento_vagas_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
